services:
  postgres:
    image: postgres:17
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - rember-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3210:3210
    environment:
      LOG_LEVEL: ${BACKEND_LOG_LEVEL}
      DATABASE_URL: ${BACKEND_DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - rember-network

networks:
  rember-network:
    driver: bridge

volumes:
  postgres_data:
