[package]
name = "rember-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.29.0"
color-eyre = "0.6.5"
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
